// <auto-generated />
using Mera.WordCounter.Server;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Mera.WordCounter.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210128165558_RealSeedDataInsertion")]
    partial class RealSeedDataInsertion
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Mera.WordCounter.Shared.Entities.Text", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Texts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "One morning, . ,  when Gregor Samsa woke"
                        },
                        new
                        {
                            Id = 2,
                            Content = "from   troubled dreams, he found himself"
                        },
                        new
                        {
                            Id = 3,
                            Content = "transformed in his bed into a    horrible vermin."
                        },
                        new
                        {
                            Id = 4,
                            Content = "He lay on his"
                        },
                        new
                        {
                            Id = 5,
                            Content = "armour-like back, and if he lifted his head a little he could see"
                        },
                        new
                        {
                            Id = 6,
                            Content = "his brown, .  belly, slightly domed and ,,,, divided by"
                        },
                        new
                        {
                            Id = 7,
                            Content = "arches into stiff sections."
                        },
                        new
                        {
                            Id = 8,
                            Content = "The bedding .. was hardly    able to cover"
                        },
                        new
                        {
                            Id = 9,
                            Content = "it and seemed"
                        },
                        new
                        {
                            Id = 10,
                            Content = " ready to slide off any moment."
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
